### PR TITLE
Enhance Snapshot struct and add ListDetail function in V3 blockstorage

### LINKED ISSUE #2403: V3 blockstorage snapshot list is using the wrong endpoint
### Currently used endpoint and the correct endpoint
The snapshot list of blockstorage v3 is using the following endpoint:
```
https://URL/v3/ADMIN_PROJECT_ID/snapshots?all_tenants=true
```
But this endpoint is missing some values (for example the project ID). To include all attributes of the snapshot the following endpoint should be used:
```
https://URL/v3/ADMIN_PROJECT_ID/snapshots/detail?all_tenants=true
```

### Code cause for this issue
This is because a error in [https://github.com/gophercloud/gophercloud/blob/master/openstack/blockstorage/v3/snapshots/urls.go](https://github.com/gophercloud/gophercloud/blob/master/openstack/blockstorage/v3/snapshots/urls.go). With the following code:
```
...
func createURL(c *gophercloud.ServiceClient) string {
	return c.ServiceURL("snapshots")
}
...
func listURL(c *gophercloud.ServiceClient) string {
	return createURL(c)
}
...
```

As comparison the url generation for the blockstorage volumes (which use the correct `detail` endpoint) [https://github.com/gophercloud/gophercloud/blob/master/openstack/blockstorage/v3/volumes/urls.go](https://github.com/gophercloud/gophercloud/blob/master/openstack/blockstorage/v3/volumes/urls.go)
```
func listURL(c *gophercloud.ServiceClient) string {
	return c.ServiceURL("volumes", "detail")
}
```

### Potential fix for this issue
This can be fixed by using the same logic for the snapshots like used for the volumes. That would look something like this:
```
func listURL(c *gophercloud.ServiceClient) string {
	return c.ServiceURL("snapshots", "detail")
}
```

### PR DESCRIPTION
**Pull request by dkokkino**
- Extended Snapshot struct to include additional fields: Progress, ProjectID, GroupSnapshotID, UserID, ConsumesQuota
- Implemented ListDetail function to retrieve detailed snapshot information from the snapshots/detail endpoint
- Added new test to validate the inclusion of additional fields and the functionality of  ListDetails

Fixes #2403

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:

Documentation: https://docs.openstack.org/api-ref/block-storage/v3/#list-snapshots-and-details

### CODE REVIEW

File: internal/acceptance/openstack/blockstorage/v3/snapshots_test.go [hunk 1]
```diff
@@ -74,6 +74,23 @@ func TestSnapshots(t *testing.T) {
 		return true, nil
 	})
```
Comment (mandre) [inline internal/acceptance/openstack/blockstorage/v3/snapshots_test.go:76]: We're missing an `th.AssertNoErr(t, err)` here, to validate that the previous call didn't return an error.

**Review by mandre — COMMENTED** [review]
This looks great. We can merge after you address the missing assert and squash your commits.

File: internal/acceptance/openstack/blockstorage/v3/snapshots_test.go (hunk 1 above)
Comment (dkokkino) [reply internal/acceptance/openstack/blockstorage/v3/snapshots_test.go:77]: Added the missing line of code and squashed my commits

**Review by mandre — APPROVED** [review]
