### PR TITLE
fix (image/v2/images): image v2 unmarshal issue

### LINKED ISSUE #3588: Image V2: cannot unmarshal string into Go struct field .images.tmp.Properties of type map[string]interface {}
### What happened?

When user provide additional metadata to an image with a key `properties`, this will cause the unmarshal of Image struct broken. 

To reproduce, create an image in glance, and add a property named `properties`

```bash
openstack image set <MY_IMAGE> --properties properties="anything, it can be {'hypervisor_type': 'qemu', 'architecture': 'x86_64'}"
```

Then, use the sdk to list that image 

```go
package main

import (
    "context"

    "github.com/gophercloud/gophercloud/v2"
    "github.com/gophercloud/gophercloud/v2/openstack"
    "github.com/gophercloud/gophercloud/v2/openstack/image/v2/images"
)

func main() {
    ctx := context.Background()

    opts, err := openstack.AuthOptionsFromEnv()
    if err != nil {
        panic(err)
    }

    providerClient, err := openstack.AuthenticatedClient(ctx, opts)
    if err != nil {
        panic(err)
    }

    listOpts := images.ListOpts{
        Name: "<MY_IMAGE>",
    }

    imageClient, err := openstack.NewImageV2(providerClient, gophercloud.EndpointOpts{})
    if err != nil {
        panic(err)
    }

    _, err := images.List(imageClient, listOpts).AllPages(ctx)   # should failed here
    if err != nil {
        panic(err)
    }
}
```

Useful debugging information to help identify the issue:

```bash
openstack image show <MY_IMAGE> --debug
```

Note the last `RESP BODY` from the debug output.

This is originally from https://github.com/canonical/openstack-exporter-operator/issues/158

### Version

v2 (current)

### PR DESCRIPTION
**Pull request by chanchiwai-ray**
This PR address the unmarshal issue when user add an additional property `properties`  to the image using `openstack image set <IMAGE> --property <KEY>=<VALUE> ...`, which collides with the field in `Image.Properties` with a type of `map[string]any`. 

Fixes #3588

See the issue above to reproduce a test case.

### CODE REVIEW

File: openstack/image/v2/images/results.go [hunk 1]
```diff
@@ -102,6 +102,7 @@ func (r *Image) UnmarshalJSON(b []byte) error {
 	type tmp Image
 	var s struct {
 		tmp
+		Properties                  string `json:"properties"`
```
Comment (kayrus) [inline openstack/image/v2/images/results.go:105]: I think it must cover both cases, when properties is a string or a map.

Comment (chanchiwai-ray) [reply openstack/image/v2/images/results.go:105]: The "properties" should not be possible to anything other than a string if you are setting it using `openstack image set --property`. I don't know if there are other ways inject additional properties though.

This what is saw when I enable debug mode

```bash
openstack image set raychan-noble-iso-test --property properties="{'hypervisor_type': 'qemu', 'architecture': 'x86_64'}" --property addition_string="hello world" --property additional_number=123 --property additional_list_number=[1,2,3] --property additional_list_string='["h", "i"]' --property addtional_bool=false --property addtional_map='{"name": "noble", "size": 100, "hidden": false}' --debug
```

```json
{
  "additional_list_number": "[1,2,3]",
  "additional_list_string": "[\"h\", \"i\"]",
  "additional_number": "123",
  "addition_string": "hello world",
  "addtional_bool": "false",
  "addtional_map": "{\"name\": \"noble\", \"size\": 100, \"hidden\": false}",
  "owner_specified.openstack.md5": "",
  "owner_specified.openstack.object": "images/raychan-noble-iso-test",
  "owner_specified.openstack.sha256": "",
  "properties": "{'hypervisor_type': 'qemu', 'architecture': 'x86_64'}",
  "name": "raychan-noble-iso-test",
  "disk_format": "iso",
  "container_format": "bare",
  "visibility": "shared",
  "size": 3303444480,
  "virtual_size": null,
  "status": "active",
  "checksum": "19fe5793f7411cfe124d9fa0c0f4d449",
  "protected": false,
  "min_ram": 0,
  "min_disk": 0,
  "owner": "dfdfed1a51504178abe8c5eeaeb8343b",
  "os_hidden": false,
  "os_hash_algo": "sha256",
  "os_hash_value": "c3514bf0056180d09376462a7a1b4f213c1d6e8ea67fae5c25099c6fd3d8274b",
  "id": "370ba8b7-3e72-4f9d-8623-7d9c95e4c28d",
  "created_at": "2025-12-18T02:05:15Z",
  "updated_at": "2025-12-18T02:42:05Z",
  "locations": [
    {
      "url": "rbd://eea9d068-c18c-11ed-8dc0-013aacb71b80/glance/370ba8b7-3e72-4f9d-8623-7d9c95e4c28d/snap",
      "metadata": {
        "store": "ceph"
      }
    }
  ],
  "direct_url": "rbd://eea9d068-c18c-11ed-8dc0-013aacb71b80/glance/370ba8b7-3e72-4f9d-8623-7d9c95e4c28d/snap",
  "tags": [],
  "self": "/v2/images/370ba8b7-3e72-4f9d-8623-7d9c95e4c28d",
  "file": "/v2/images/370ba8b7-3e72-4f9d-8623-7d9c95e4c28d/file",
  "schema": "/v2/schemas/image",
  "stores": "ceph"
}
```

Comment (kayrus) [reply openstack/image/v2/images/results.go:105]: Ok, I see. Just to clarify, which OpenStack component actually consumes these image `properties`? Nova? I've been looking through the Nova source and documentation, and it appears that `hypervisor_type` is expected to be a top-level image attribute, not nested under `properties`.
According to the Nova scheduling documentation, the scheduler looks for `hypervisor_type` directly on the image object: https://github.com/openstack/nova/blob/3e5a2dbad73ff61d27db8750480e2c0b52133676/doc/source/admin/scheduling.rst?plain=1#L504

Comment (chanchiwai-ray) [reply openstack/image/v2/images/results.go:105]: The above is just an example that I got from a live environment that I have, it could be provided by a user or some programs (tbh, not sure where it comes from). But some users reported in the openstack-exporter that by having `--property properties="something"` could break the unmarshal of `Image`.

**Comment by chanchiwai-ray** [comment]
I will provide some functional tests later

**Review by kayrus — APPROVED** [review]
LGTM, thanks!
