### PR TITLE
Manila: add messages support

### LINKED ISSUE #1358: Manila: add messages support
In order to identify the exact error message of failed manila share, [messages API](https://developer.openstack.org/api-ref/shared-file-system/#user-messages-since-api-2-37) could be used.

### PR DESCRIPTION
**Pull request by kayrus**
Resolves #1358

### CODE REVIEW

**Comment by kayrus** [comment]
recheck

**Comment by jtopjian** [comment]
If it's happening here, too, I'm leaning on an OpenLab problem. Since it's the weekend, it might not get resolved for another day or two.

**Comment by kayrus** [comment]
recheck

**Comment by kayrus** [comment]
Ready for review.

File: acceptance/openstack/sharedfilesystems/v2/messages/messages.go [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+	err := messages.Delete(client, message.ID).ExtractErr()
+	if err != nil {
+		t.Fatalf("Failed to delete message %s: %v", message.ID, err)
+	}
+
+	t.Logf("Deleted message: %s", message.ID)
+}
+
+// PrintMessage will print a message and all of its attributes.
+func PrintMessage(t *testing.T, message *messages.Message) {
```
Comment (jtopjian) [inline acceptance/openstack/sharedfilesystems/v2/messages/messages.go]: Can `tools.PrintResource` be used instead? If you really want to see the `CreatedAt` and `ExpiresAt` times, you should be able to do `tools.PrintResource(t, message.CreatedAt)`.

File: openstack/sharedfilesystems/v2/messages/results.go [hunk 2]
```diff
@@ -0,0 +1,101 @@
...
+
+import (
+	"encoding/json"
+	"time"
+
+	"github.com/gophercloud/gophercloud"
+	"github.com/gophercloud/gophercloud/pagination"
+)
+
+const MinimumManilaMessagesMicroVersion = "2.37"
```
Comment (jtopjian) [inline openstack/sharedfilesystems/v2/messages/results.go]: microversions are set during the request, so if we would be adding constants like this, it would go in `requests.go` instead. However, let's remove this - this opens the door to having Gophercloud maintain these kinds of contants for every microversion version and feature.

File: acceptance/openstack/sharedfilesystems/v2/messages/messages.go (hunk 1 above)
Comment (kayrus) [reply acceptance/openstack/sharedfilesystems/v2/messages/messages.go]: Done
