### PR TITLE
Fix value_specs implementation

### LINKED ISSUE #2870: ValueSpecs in port CreateOpts is a no-op
I was reading https://github.com/gophercloud/gophercloud/pull/2537, which adds `value_specs` to ports. The doc link in the PR points to the Heat documentation, where it is a parameter. It is documented as:
> Extra parameters to include in the request.

The gophercloud implementation includes a `value_specs` parameter in the port creation request. However, I couldn't find any evidence that neutron supports this parameter. Digging in to the implementation in Heat, I think the purpose of this field is to add arbitrary top-level fields to the request. i.e. There is no `value_specs` field.
 I found some validation of `value_specs` which supports that:
https://github.com/openstack/heat/blob/2df46d4c59140255ece640896019bfca03437388/heat/engine/resources/openstack/neutron/neutron.py#L49-L62

Also, the only use of it I could find uses it in this way:
https://github.com/openstack/heat/blob/2df46d4c59140255ece640896019bfca03437388/heat/engine/resources/openstack/nova/server_network_mixin.py#L131-L133

I think we should re-examine the use case for this API. It is possible that it's required to support out-of-tree neutron drivers. If so, we should fix it to behave the same way as it does in Heat. However, it's clear that nobody is currently using it. This also opens an argument for removing it[^1], especially as it's an unusual API backdoor.

I have a suspicion that it was just an escape-hatch in Heat so they didn't have to add every port parameter to Heat. I note that in Heat ports have binding:vnic_type, but not binding:(host_id|profile|vif_details|vif_type). Gophercloud does have these, though:
https://pkg.go.dev/github.com/gophercloud/gophercloud@v1.8.0/openstack/networking/v2/extensions/portsbinding. Is it possible this isn't required in gophercloud?

[^1]: Or marking it deprecated with a note that it's a no-op, as API stability guarantees require.

### PR DESCRIPTION
**Pull request by lentzi90**
The current implementation does not do anything useful. The key-pairs must be extracted and added directly in the body instead of under "value_specs".

This commit fixes the implementation and also adds validation of the value_specs based on what is done in Heat. There are some banned keys that are not allowed in value_specs, and values are not allowed to overwrite existing fields either.

Fixes #2870

### CODE REVIEW

File: openstack/networking/v2/ports/requests.go [hunk 1]
```diff
@@ -1,9 +1,12 @@
 package ports
 
 import (
+	"errors"
 	"fmt"
 	"net/url"
 
+	"golang.org/x/exp/slices"
```
Comment (lentzi90) [inline openstack/networking/v2/ports/requests.go:8]: This is in the standard library from go 1.21 so I hope it is ok to use already.
https://pkg.go.dev/slices

Comment (pierreprinetti) [reply openstack/networking/v2/ports/requests.go:8]: what you are importing here is the experimental package that went on being added to the stdlib as `"slices"` in Go v1.21. I am bumping the Go version in https://github.com/gophercloud/gophercloud/pull/2686; once it merges you can rebase and use `"slices"` directly.

Comment (pierreprinetti) [reply openstack/networking/v2/ports/requests.go:8]: actually, the package you import uses generics. This patch is not backportable anyway as-is.

File: openstack/networking/v2/ports/requests.go [hunk 2]
```diff
@@ -130,7 +133,36 @@ type CreateOpts struct {
...
+// from the reqeust body. It will return error if the value specs would overwrite
+// an existing field or contains forbidden keys.
+func AddValueSpecs(body map[string]interface{}) (map[string]interface{}, error) {
+	bannedKeys := []string{"shared", "tenant_id"}
+	port := body["port"].(map[string]interface{})
+
+	if port["value_specs"] != nil {
+		for k, v := range port["value_specs"].(map[string]interface{}) {
+			if slices.Contains(bannedKeys, k) {
+				return nil, errors.New(fmt.Sprintf("forbidden key in value_specs: %s", k))
```
Comment (pierreprinetti) [inline openstack/networking/v2/ports/requests.go:154]:
```suggestion
				return nil, fmt.Errorf("forbidden key in value_specs: %q", k)
```

File: openstack/networking/v2/ports/requests.go [hunk 3]
```diff
@@ -130,7 +133,36 @@ type CreateOpts struct {
...
+			}
+			if _, ok := port[k]; ok {
+				return nil, errors.New(fmt.Sprintf("value_specs would overwrite key: %s", k))
```
Comment (pierreprinetti) [inline openstack/networking/v2/ports/requests.go:157]:
```suggestion
				return nil, fmt.Errorf("value_specs would overwrite key: %q", k)
```

File: openstack/networking/v2/ports/requests.go [hunk 4]
```diff
@@ -130,7 +133,36 @@ type CreateOpts struct {
...
+	}
+
+	return AddValueSpecs(body)
+}
+
+// AddValueSpecs expands the 'value_specs' object and removes 'value_specs'
+// from the reqeust body. It will return error if the value specs would overwrite
+// an existing field or contains forbidden keys.
+func AddValueSpecs(body map[string]interface{}) (map[string]interface{}, error) {
+	bannedKeys := []string{"shared", "tenant_id"}
```
Comment (pierreprinetti) [inline openstack/networking/v2/ports/requests.go:148]: Why only these two?

Comment (lentzi90) [reply openstack/networking/v2/ports/requests.go:147]: I copied what Heat is doing: https://github.com/openstack/heat/blob/dd7319e373b88812cb18897f742b5196a07227ea/heat/engine/resources/openstack/neutron/neutron.py#L59
Not sure about why exactly these two were banned though

**Comment by pierreprinetti** [comment]
Did we ever return anything in the `ValueSpecs` field of `ports.Port`?

**Comment by EmilienM** [comment]
@lentzi90 don't heat remove value_specs from the body before sending to neutron? shouldn't we do the same?
https://github.com/openstack/heat/commit/d4b6f37ab57226f1e4d90ebb8ac0ba127d4ad973

**Comment by lentzi90** [comment]
> @lentzi90 doesn't Heat remove value_specs from the body before sending to neutron? shouldn't we do the same? [openstack/heat@d4b6f37](https://github.com/openstack/heat/commit/d4b6f37ab57226f1e4d90ebb8ac0ba127d4ad973)

Yes! I hope it is what I'm doing with

```go
delete(port, "value_specs")
```

So first we take all keys under `value_specs`, check if they are banned, check if they would overwrite an existing field, if not we add them to the body and finally remove the `value_specs` field.

**Comment by lentzi90** [comment]
> Did we ever return anything in the `ValueSpecs` field of `ports.Port`?

I don't think so

**Comment by lentzi90** [comment]
Any way to re-trigger that one failed test besides pushing again?
Everything passed already before I changed `errors.New` -> `fmt.Errorf`, which is trivial, so it is probably a flake...

**Comment by pierreprinetti** [comment]
I have manually retriggered the run

File: openstack/networking/v2/ports/requests.go (hunk 1 above)
Comment (EmilienM) [reply openstack/networking/v2/ports/requests.go:7]: Please rebase on main and use `slices` directly since https://github.com/gophercloud/gophercloud/pull/2883 has merged now. Thanks!

File: openstack/networking/v2/ports/requests.go (hunk 4 above)
Comment (EmilienM) [reply openstack/networking/v2/ports/requests.go:147]: Fine by me, the list can evolve later. However I'll like to see a comment explaining that we took it from Heat without knowing much about why these 2 :smile:

**Review by EmilienM — CHANGES_REQUESTED** [review]
Minor change is required before we can merge, I think today.

File: .gitignore [hunk 5]
```diff
@@ -2,3 +2,5 @@
 .idea
 .vscode
 testing_*.coverprofile
+# Development container configuration (https://containers.dev/)
```
Comment (EmilienM) [inline .gitignore:5]: unrelated change, maybe via separate commit

Comment (lentzi90) [reply .gitignore:5]: I can remove it, no worries :slightly_smiling_face:

**Review by EmilienM — APPROVED** [review]

**Comment by EmilienM** [comment]
unit test job is broken but it's not your PR

**Comment by EmilienM** [comment]
LGTM for me. I'll let a chance to other reviewers to have another look as well (cc @pierreprinetti).

**Comment by EmilienM** [comment]
might need a rebase in fact

File: openstack/networking/v2/ports/requests.go [hunk 6]
```diff
@@ -130,7 +131,37 @@ type CreateOpts struct {
...
+	}
+
+	return AddValueSpecs(body)
+}
+
+// AddValueSpecs expands the 'value_specs' object and removes 'value_specs'
+// from the request body. It will return error if the value specs would overwrite
+// an existing field or contains forbidden keys.
+func AddValueSpecs(body map[string]interface{}) (map[string]interface{}, error) {
+	// Banned the same as in heat. See https://github.com/openstack/heat/blob/dd7319e373b88812cb18897f742b5196a07227ea/heat/engine/resources/openstack/neutron/neutron.py#L59
```
Comment (dulek) [inline openstack/networking/v2/ports/requests.go:146]: Would probably be better to link to opendev.org instead of GitHub mirrors, no big deal.

**Review by dulek — COMMENTED** [review]
Looks okay from my perspective.

File: openstack/networking/v2/ports/requests.go (hunk 6 above)
Comment (lentzi90) [reply openstack/networking/v2/ports/requests.go:146]: Ah my bad :facepalm: 
Just say the word and I'll update...
